logging:
    level:
        bio:
            overture: TRACE
            overture.maestro.domain.entities.indexing.rules.IDExclusionRule: INFO
        org:
            apache:
                kafka:
                    clients: WARN
        root: INFO
maestro:
    elasticsearch:
        client:
            connection-timeout: 5000
            docs-per-bulk-req-max: 5000
            retry:
                max-attempts: 3
                wait-duration-millis: 500
            socket-timeout: 10000
        cluster-nodes: localhost:9200, localhost:9201
        indexes:
            file-centric:
                alias: file_centric
    exclusion-rules:
        file-name: exclusion-rules.yml
    failure-log:
        dir: ${user.home}/logs/maestro
        enabled: true
    kafka:
        broker: localhost:9092
        indexing-topic: maestro-index-requests
    repositories:
    -   code: collab
        country: CA
        dataPath: /oicr.icgc/data
        metadataPath: /oicr.icgc.meta/metadata
        name: collaboratory
        organization: ICGC
        storageType: S3
        url: https://song.cancercollaboratory.org
    -   code: aws
        country: US
        metadataPath: /oicr.icgc.meta/metadata
        name: aws virginia
        organization: ICGC
        storageType: S3
        url: https://virginia.song.icgc.org
    song:
        indexable-study-status: PUBLISHED
        max-retries: 3
        timeout-sec: 100
management:
    endpoint:
        health:
            show-details: ALWAYS
    endpoints:
        web:
            exposure:
                include: '*'
server:
    port: 80
spring:
    application:
        name: maestro
    cloud:
        stream:
            bindings:
                input:
                    destination: ${maestro.kafka.indexing-topic}
            kafka:
                binder:
                    brokers: ${maestro.kafka.broker}
    output:
        ansi:
            enabled: ALWAYS
