# Default values for maestro.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: overture/maestro
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 11235

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: maestro.local
      paths: []
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

# use this to inject all the env vars you need to override application.yaml
# see _examples/provide-env/values.yaml
extraEnv: {}

# this is useful to integrate with vault 
rbac:
  create:
    tokenReview: false

appVolume:
  size: 1Gi
  storageClass: standard
  mountPath: /app-data

containerPort: 80