{{- if .Values.ingressApi.enabled -}}
{{- $fullName := include "ego.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-api
  labels:
    app.kubernetes.io/name: {{ include "ego.name" . }}
    helm.sh/chart: {{ include "ego.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.ingressApi.annotations }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingressApi.tls }}
  tls:
  {{- range .Values.ingressApi.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.ingressApi.host }}
      http:
        paths:
          - path: /api/(.*)
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
{{- end }}
