apiVersion: v1
kind: Secret
metadata:
  name: {{ include "song.fullname" . }}
  labels:
{{ include "song.labels" . | indent 4 }}
{{- if .Values.extraLabels }}
{{ include ".Values.extraLabels" . | indent 4 }}
{{- end }}
type: Opaque
data:
{{- if .Values.backup.enabled }}
  s3-secretKey: {{ .Values.backup.s3.secretKey | b64enc | quote }}
{{- end }}
  id-authtoken: {{ .Values.appConfig.id.federated.auth.bearer.token | b64enc | quote }}
  score-accessToken: {{ .Values.appConfig.score.accessToken | b64enc | quote }}
  auth-server-client-secret: {{ .Values.appConfig.auth.server.clientSecret | b64enc | quote }}
