apiVersion: v1
kind: Service
metadata:
  name: {{ include "song.server.fullname" . }}
  labels:
  {{ include "song.labels" . | indent 4 }}
  {{- if .Values.extraLabels }}
  {{ include ".Values.extraLabels" . | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "song.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
