kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "maestro.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "maestro.name" . }}
    helm.sh/chart: {{ include "maestro.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.appVolume.size | quote }}
{{- if .Values.appVolume.storageClass }}
  storageClassName: {{ .Values.appVolume.storageClass }}
{{- end }}
