apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "score.fullname" . }}
  labels:
    app: {{ include "score.name" . }}
    chart: {{ include "score.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "score.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "score.name" . }}
        release: {{ .Release.Name }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: score-server
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: {{ .Values.appConfig.springProfiles }}
          - name: SERVER_PORT
            value: {{ quote .Values.appConfig.storageServer.port }}
          - name: OBJECT_SENTINEL
            value: {{ .Values.appConfig.storageServer.sentinel }}
          - name: BUCKET_NAME_STATE
            value: {{ .Values.appConfig.storageServer.stateBucket }}
          - name: BUCKET_NAME_OBJECT
            value: {{ .Values.appConfig.storageServer.dataBucket }}
          - name: COLLABORATORY_DATA_DIRECTORY
            value: {{ .Values.appConfig.storageServer.dataDir }}
          - name: UPLOAD_PARTSIZE
            value: {{ quote .Values.appConfig.storageServer.partSize }}
          - name: UPLOAD_CONNECTION_TIMEOUT
            value: {{ quote .Values.appConfig.storageServer.connectionTimeout }}
          - name: METADATA_URL
            value: {{ .Values.appConfig.song.serverUrl }}
          - name: S3_ENDPOINT
            value: {{ .Values.appConfig.objectStorage.url }}
          - name: S3_ACCESSKEY
            value: {{ .Values.appConfig.objectStorage.accessKey }}
          - name: S3_SECRETKEY
            valueFrom:
              secretKeyRef:
                name: {{ template "score.fullname" . }}
                key: s3-secretKey
          - name: S3_SIGV4ENABLED
            value: {{ .Values.appConfig.objectStorage.sigV4Enabled | quote }}
          - name: AUTH_SERVER_URL
            value: {{ .Values.appConfig.authServer.url }}
          - name: AUTH_SERVER_TOKENNAME
            value: {{ .Values.appConfig.authServer.tokenName }}
          - name: AUTH_SERVER_CLIENTID
            value: {{ .Values.appConfig.authServer.clientId }}
          - name: AUTH_SERVER_CLIENTSECRET
            valueFrom:
              secretKeyRef:
                name: {{ template "score.fullname" . }}
                key: auth-clientSecret
          - name: AUTH_SERVER_SCOPE_DOWNLOAD_SYSTEM
            value: {{ .Values.appConfig.authServer.scope.download.system }}
          - name: AUTH_SERVER_SCOPE_DOWNLOAD_STUDY_PREFIX
            value: {{ .Values.appConfig.authServer.scope.download.study.prefix }}
          - name: AUTH_SERVER_SCOPE_DOWNLOAD_STUDY_SUFFIX
            value: {{ .Values.appConfig.authServer.scope.download.study.suffix }}
          - name: AUTH_SERVER_SCOPE_UPLOAD_SYSTEM
            value: {{ .Values.appConfig.authServer.scope.upload.system }}
          - name: AUTH_SERVER_SCOPE_UPLOAD_STUDY_PREFIX
            value: {{ .Values.appConfig.authServer.scope.upload.study.prefix }}
          - name: AUTH_SERVER_SCOPE_UPLOAD_STUDY_SUFFIX
            value: {{ .Values.appConfig.authServer.scope.upload.study.suffix }}
{{- if .Values.extraEnv }}
  {{ range $key, $value := .Values.extraEnv }}
          - name: {{ $key }}
            value: {{ $value | quote }}
  {{- end }}
{{- end }}


status: {}
