apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "score.fullname" . }}
  labels:
    app: {{ include "score.name" . }}
    chart: {{ include "score.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "score.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "score.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: score-server
          restartPolicy: Always
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: {{ .Values.appConfig.springProfiles }}
          - name: SERVER_PORT
            value: {{ quote .Values.appConfig.storageServer.port }}
          - name: OBJECT_SENTINEL
            value: {{ .Values.appConfig.storageServer.sentinel }}
          - name: BUCKET_NAME_STATE
            value: {{ .Values.appConfig.storageServer.stateBucket }}
          - name: BUCKET_NAME_OBJECT
            value: {{ .Values.appConfig.storageServer.dataBucket }}
          - name: COLLABORATORY_DATA_DIRECTORY
            value: {{ .Values.appConfig.storageServer.dataDir }}
          - name: UPLOAD_PARTSIZE
            value: {{ quote .Values.appConfig.storageServer.partSize }}
          - name: UPLOAD_CONNECTION_TIMEOUT
            value: {{ quote .Values.appConfig.storageServer.connectionTimeout }}
          - name: METADATA_URL
            value: {{ .Values.appConfig.song.serverUrl }}
          - name: S3_ENDPOINT
            value: {{ .Values.appConfig.objectStorage.url }}
          - name: S3_ACCESSKEY
            value: {{ .Values.appConfig.objectStorage.accessKey }}
          - name: S3_SECRETKEY
            value: {{ .Values.appConfig.objectStorage.secretKey }}
          - name: S3_SIGV4ENABLED
            value: {{ .Values.appConfig.objectStorage.sigV4Enabled | quote }}
          - name: AUTH_SERVER_URL
            value: {{ .Values.appConfig.authServer.url }}
          - name: AUTH_SERVER_CLIENTID
            value: {{ .Values.appConfig.authServer.clientId }}
          - name: AUTH_SERVER_CLIENTSECRET
            value: {{ .Values.appConfig.authServer.clientSecret }}
          - name: AUTH_SERVER_UPLOADSCOPE
            value: {{ .Values.appConfig.authServer.downloadScope }}
          - name: AUTH_SERVER_DOWNLOADSCOPE
            value: {{ .Values.appConfig.authServer.uploadScope }}
{{- if .Values.extraEnv }}
  {{ range $key, $value := .Values.extraEnv }}
          - name: {{ $key }}
            value: {{ $value | quote }}
  {{- end }}
{{- end }}


status: {}
