apiVersion: v1
kind: Secret
metadata:
  name: {{ include "score.fullname" . }}
  labels:
    app: {{ include "score.name" . }}
    chart: {{ include "score.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{- if .Values.appConfig.objectStorage.secretKey }}
  s3-secretKey: {{ .Values.appConfig.objectStorage.secretKey | b64enc | quote }}
  {{- else }}
  s3-secretKey: {{ randAlphaNum 15 | b64enc | quote }}
  {{- end }}
  {{- if .Values.appConfig.authServer.clientSecret }}
  auth-clientSecret: {{ .Values.appConfig.authServer.clientSecret | b64enc | quote }}
  {{- else }}
  auth-clientSecret: {{ randAlphaNum 15 | b64enc | quote }}
  {{- end }}
