# Default values for song.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: overture/song-server
  tag: 2.0.0
  pullPolicy: IfNotPresent

backupImage:
  repository: overture/song-postgres-backup-s3
  tag: 0.1.6
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - song.local
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

volumeSize: 20Gi

extraEnv: {}

appConfig:
  profiles: "prod,secure,default"
  id:
    idURL: https://id.local
    authToken: "123"
    realIDs: false
  flyway:
    enabled: true
    locations: classpath:flyway/sql,classpath:db/migration
  auth:
    server:
      scope:
        study:
          prefix: "song."
          suffix: ".WRITE"
        system: "song.WRITE"
      url: https://auth.local/oauth/check_token
      clientID: metadata
      clientSecret: test
  score:
    url: https://storage.local
    accessToken: "321"

postgres:
  postgresUsername: postgres
  postgresPassword: password
  postgresDb: song

backup:
  enabled: false
  schedule: "1 * * * *"
  dbName: song
  awsAccessKey: #
  awsSecretKey: #
  endpointURL: "https://object.local:9080"
