apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "maestro.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "maestro.name" . }}
    helm.sh/chart: {{ include "maestro.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "maestro.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "maestro.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      # https://github.com/helm/helm/blob/master/docs/charts_tips_and_tricks.md#automatically-roll-deployments-when-configmaps-or-secrets-change
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configMap.yaml") . | sha256sum }}
    spec:
      # create a volume for the application config map
      volumes:
        - name: maestro-config-volume
          configMap:
            name: maestro-app-config
            items:
              - key: application.yml
                path: application.yml
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # mount the config map as a file in the volume specified by the image
          volumeMounts:
            - name: maestro-config-volume
              mountPath: "/app-config"
              readOnly: true
          # configure spring to read from the mounted volume path above.
          env:
            - name: SPRING_CONFIG_LOCATION
              value: "file:/app-config/"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
    affinity:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
    tolerations:
      {{- toYaml . | nindent 8 }}
    {{- end }}